### ISSUE TITLE
here

### ISSUE THREAD

**Issue by machiavel23** [VBPXKSMI/Open-CYOAI-Project#166]
I see you're finally unflagged. I sent you a colaborator invite on the other repo, it should help you retrieve everything. tell me when you're done retrieving for i can get the fuck out of this reddit-tier thread

**Comment by machiavel23** [comment]
fuck it, it directly send you a transferownership request. accept it and the repo will be all yours.

**Comment by VBPXKSMI** [comment]
@machiavel23 My account is unflagged now, you can see I changed of name too, nothing special.
Rather than accepting ownership of that repo, I will transplant all changes done there to here, as we have the commits history, issues, etc, here. I'm halfway done, probably should be done by the end of the day.
The other account (and its repository) should be kept separated, just in case my account gets flagged again.

Don't make any announcements yet, I will let you know when to do it through here, then you should change that repo to be private, so that it doesn't generate confussion. Then I will delete this issue.

Also, I am having issues trying to replicate the "ignored/hidden issue template folder", if you can upload it here in the master branch, all the better.
Speaking of which, I hope you continue contributing, as your help and work were very good IMO as I have already expressed before. But I will understand if you don't want to continue, as this is a very credditless endeavor. Either way, let me know your thoughts.

**Comment by TemporaryAccountForUndercoverOperation** [comment]
Using this account in case the fucker watch where the others are commenting. I swear you if I ever find his neck....

Anyway. If you want, I can push the complete repo here as well as the wiki, to save you time. unless you work on the wiki here, i can only push the repo then. will wait your answer, and will act accordingly. will push the templates meanwhile with this account to prove you it's me.

If I understand correctly, you want my repo to go private when everything is fine, that's it? I'm confused with the "that repo", I don't get which one it is

I took the time to cooldown, and I'm ready to continue, as you can already see with the output I'm working on. I'm taking quite some recoil now. Sorry for the trouble.

**Comment by TemporaryAccountForUndercoverOperation** [comment]
just pushed the templates. I can push all the other changes as easily if you wish, just tell me here, or write "bratislava" in some post in the thread.

**Comment by TemporaryAccountForUndercoverOperation** [comment]
https:==github.com=storybro=storybro=pull=19

seriously, those fuckers...

**Comment by VBPXKSMI** [comment]
@TemporaryAccountForUndercoverOperation  
>Anyway. If you want, I can push the complete repo here as well as the wiki, to save you time. unless you work on the wiki here, i can only push the repo then. will wait your answer, and will act accordingly. still, i'm pushing the templates now.

It may be a hassle but I will just manually copy-paste everything from the "Open CYOAI" repository to here, just to be sure, and I will also change the pertaining links of both the Colabs and the Wiki.
You can continue working on improvements there until we move back to here, I will copy any change you make.
Before commiting any change in your repo, just make sure to refresh this page in case I have everything ready for the move and I tell you that here. Also, try to not commit many changes to the Wiki, or at least communicate them first here, so that I can copy them.
Hopefully, I should finish by the end of the day.

>If I understand correctly, you want my repo to go private when everything is fine, that's it? I'm confused with the "that repo", I don't get which one it is

Correct, having more than 1 repository will just confuse brainlets, so that's why the "Open CYOAI" repository should go private. In the case something happens to this account, we could make "that" other repository public again, and continue working on there.

>I took the time to cooldown, and I'm ready to continue, as you can already see with the output I'm working on. I'm taking quite some recoil now. Sorry for the trouble.

I'm glad, and don't worry, shit like this happens to the best of us, and Anons being faggots doesn't help honestly.

>https:==github.com=storybro=storybro=pull=19
seriously, those fuckers...

Saw that, cunts are too sure of themselves they can't even check the code.
I even remember when 1 Anon posted about his version of that code (I implemented it based on that post), should be in the archives (EDIT: just found it, https://arch.b4k.co/v/thread/489190597/#q489203889, I think that code doesn't appear anywhere else in the internet but I'm not sure, can you check?). I only made small adjustements to it so that we could get the fastest crash as possible (10 seconds), and I spent a whole hour doing the tests until deciding we couldn't get faster than that. The change was "quite" an improvement since we went from the crash needing 80-90 seconds to just 10. 
Anyway (at least for me) I didn't need to use that cell for a long time, it seems that the Colab opens with 25GB of RAM automatically almost always, probably due to the ammount of people using it.

Speaking of licenses, the Colab made by the discord moderator "Evren" that it is pinned in their channels, is based on ours one, especifically on the Old Colab, even copied the "Steps" on how to run the cells and in what order. I cannot remember if it was made before or after the implementing of the AGPL license, think it was after but will have to check. Even then, lets not bring this up yet until we are sure.
Link: 
https:// 
colab.research.google.com/drive/
19_0khNTwlKGYfWRhm7-ZHUGlX3mX9AfD

EDIT: checked it just now (last time I checked it was 1 week ago), it seems they do credit "Kornilov1", although I would prefer if they also credited "4chan Anons" too, since that was the porpuse of the license, not for the credit to go to me. 
Wondering if we should/could make it even more clear we want the credit to go to "4chan Anons" and not just to whoever happens to be maintening the repository at the time. Otherwise, what would be the fucking point?

>but they're right about the illegal license change. the mit allow sublicensing, we have to put (((HE)))'s license on top with a "as of commit ####" like thadunge did
EDIT: wait, no... they're actually wrong!! my repo is not a fork of anyone, and the code clearly doesn't look like theirs!

Honestly, my understanding of the licenses and their working is quite limited. I wish that Anon, that helped set up them in the first place, was here to help.
The license and the author's disclaimer is a fucking hassle, and I fucking wish we could be done with them once and for all. Spending time in that just slows down any progress in the other more important matters. Not saying they should be ditched, just that I wished they could be done with, set in stone, and never have to look at them again.

**Comment by TemporaryAccountForUndercoverOperation** [comment]
Got it. Don't worry for the wiki, I don't edit it. Also, I checked evren colab and yep, we should indeed make it clearer that they have to credit 4chan and not just the repo maintainer.

I did a quick research and haven't been able to found the *= method either

**Comment by VBPXKSMI** [comment]
@TemporaryAccountForUndercoverOperation 
Finally got the repository in shape and ready to be used (despite me having to use a cellphone for the final tweakings).
I think I didn't miss anything, not in the Colab files nor in the Wiki links, but can you do a quick check to see if everything is correct (i.e. if I didn't miss any of your Colab commits, or if the Wiki links lead to outside Wiki pages)?

I think we can announce the repo move when I make the new thread on /vg/. 
How do you think I should announce it? Something like this?:
>Kornilov here:
We moved back to the original repository (finally). Everything is the same as the one used until recently, and that repository will now go private and only will be used in case this one gets shut down again.
>
>Works on the Wiki will continue as soon as I have decent internet connection again (phoneposting right now because of a fucking storm outside).
>
>That's all.

Once I make that post I will delete this issue and you should go private and start working in this repo instead (I assume that through your original account).
Also, you should copy the only issue you have open in the other repository. If you can't do it directly, just copy-paste the texts and open the issue here.

**Comment by VBPXKSMI** [comment]
Unrelated to the previous comment (that's why I made a new one).

How do you think we should proceed in regards to the Colab? 
I am talking about if we should transplant most "only visual" changes from the new Colab to the Old one, and leaving Anons decide which one to use.
I am saying that because, despite being nearly 100% sure the disconnects are only Google's fuckery, I am still not sure if the Old Colab is really more stable or if it's just a placebo effect thing. 

Obviously the works should continue being first and foremost in the new one, I am just asking if we should bring some of the QoL changes to the Old one, even knowing it would be a fucking hassle.

**Comment by TemporaryAccountForUndercoverOperation** [comment]
ah fuck, I just committed the OK in dev maincell for the customization. make sure to take it! it's the latest. Won't commit until the move.
7 b 1 c 5 9 7

I should be able to transfer the issue with the machivel23 account, it's a colaborator on both repo. If I can't, I'll copy-paste yeah.

For the old colab, the answer is in the wiki
![considering](https://user-images.githubusercontent.com/59630055/72040184-1071a800-32a8-11ea-849c-4f116c74db19.jpg)

I know it's an edit of mine but I don't think we should push anything in it, and just let the time makes its work on it. There's a point when we HAVE to move on if we want things to continue. If you want to maintain it a bit, it'll be your work. I already have too much to do in the new one, sorry.

Announcing the move for the next OP sounds like a good idea, the text seems fine too. Before that though, you should add

>This repository is licensed under AGPL conditions, and any code taken from it must be credited to 4chan's Anonymous.

to readme.md

Finally, I have a small request for next op. I'd like to know what people want first between those options:
-a model selector depending on the megafolder
-an easy configurator for clover's config.ini


Also, it seems the fuckers got sunned by the last comment i made lmao

**Comment by VBPXKSMI** [comment]
Second post of the thread (after the usual one as OP):

Kornilov here:
We moved back to the original repository (finally). 
Everything is the same as the one used until recently, and that repository will now go private and will only be used in the case this one gets shut down again.

Works on the Wiki will continue as soon as I have decent internet connection again (phoneposting right now because of a fucking storm outside that ruins my connection). 
If you want to contribute to the Wiki, you (probably) will need to have a GitHub account so that I can add you as a contributor. 
Just ask in the thread if you would like to do so but you will have to had contribute something (not related to Wiki contributions of course)  before so that I know you can be trusted with handling the Wiki. Access and which tasks each one will handle would be on a case by case basis.


IMPORTANT, READ THIS PLEASE, AND SHARE YOUR OPINION:
What do you Anons want first between these options for the Colab?:
>     >a model selector depending on MegAnon's folder (https://mega.nz/#F!51ED1CSA!YbifAmboqSLCrr3Y78axqw) (also maybe depending on the others megafolders too, until they are added to MegAnon's one).
>     >an easy configurator for Clover's config.ini

That's all.

**Comment by TemporaryAccountForUndercoverOperation** [comment]
checked.
Old Open CYOAI ipynb, the wiki link is wrong in "About the game"
that's all.

everything seems good, as well as the op.

for (((HER))) credits, I admit it bugs me, but it would sound like another provokation from us to them, I really have doubts about it. Still, she seems more reasonable than Wau, so maybe asking her nicely in a private message could work. Or at least ask her to redo the link to thee actual repo (which will have anons credit in readme.md anyway.)

As for linking the archive in (((THE))) pull request, it would be fun, but unnecessary unless they respond something very retarded, which apparently won't happen. We better preserve that bullet for when we'll need it. We don't have that much after all, and are already quite fragilized with our poor half-done disclaimer. For now, we have the advantage in that convo, no need to overpush and risk a backflame.

I'm 99% sure we can't do anything for the glitch and that most of the fault is because we use free spare server power. I admit that having more code in the cell COULD provoke more disconnections, but I really doubt it, considering some notebooks I saw, and all the results when you google "colab disconnect". Seriously, the first result point to the small autoclick function xD. will probably implement it in the cell in some way tho, can't hurt to be cautious. Thaat's why I think we should just let the old colab die of age in peace.

I'm ready to private the other repo when the new thread appear.

**Comment by VBPXKSMI** [comment]
@TemporaryAccountForUndercoverOperation 
Corrected the link in the Old Colab.
Won't do anything regarding the cunts.
Regarding Evren, I will see what can be done, but will wait a week or two to see if """"she"""" does something on her own.

Will make the new thread shortly after this comment and then delete this issue.
Won't make anymore changes here as I'm doing everything through my phone, and is a fucking pain in the ass (wasting too much time honestly). May still lurk the thread for a bit and then just go to sleep.

**Comment by OpenCYOAI** [comment]
ready when you are.
